# Generated by Django 5.2.15 on 2026-06-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_riskscore_risk_level_alter_riskscore_user_riskevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskscore',
            name='decision',
            field=models.CharField(default='ALLOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='LOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
