# Generated by Django 5.2.15 on 2026-06-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_loginhistory_status_alter_device_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='browser',
            field=models.CharField(max_length=100),
        ),
    ]
