# Generated by Django 5.2.15 on 2026-06-18 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudcase',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fraudcase',
            name='fraud_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fraudcase',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_cases', to='transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('PAYMENT', 'PAYMENT'), ('TRANSFER', 'TRANSFER'), ('WITHDRAWAL', 'WITHDRAWAL'), ('DEPOSIT', 'DEPOSIT')], default='TRANSFER', max_length=50),
        ),
    ]
